In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

In [2]:
!pip install trimesh

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 704.4/704.4 kB 12.6 MB/s eta 0:00:00a 0:00:01


In [4]:
import torch
import torch.nn as nn
import json
import numpy as np
import pandas as pd
import torch.optim as optim
import torchvision.transforms as transforms
from PIL import Image
from torch.utils.data import DataLoader, Dataset
import trimesh
import scipy.io
from torchvision.datasets import ImageFolder
import sys
sys.path.append('/kaggle/input/models/byop-2425/models')
from gan import Discriminator, Generator
# import sys
# sys.path.append("../models")
# from gan import Discriminator, Generator

In [6]:
mesh = trimesh.load('/kaggle/input/dataset/model/bed/IKEA_BEDDINGE/model.obj')
mesh_v = list(mesh.geometry.values())[0]
vertices = np.array(mesh_v.vertices)
faces = np.array(mesh_v.faces)
print(vertices)
print(faces)

[[-0.43324038 -0.07641411  0.10654314]
 [-0.43324038 -0.07641411  0.10654314]
 [-0.43324038 -0.07641411  0.10654314]
 [ 0.43324038 -0.07641411 -0.22230652]
 [ 0.43324038 -0.07641411  0.10654314]
 [ 0.43324038 -0.07641411  0.10654314]
 [ 0.43324038 -0.07641411  0.10654314]
 [-0.43324038 -0.07641411 -0.22230652]
 [-0.43324038 -0.07641411 -0.22230652]
 [-0.43324038 -0.07641411 -0.22230652]
 [-0.43324038 -0.0459173  -0.22230652]
 [-0.43324038 -0.0459173  -0.22230652]
 [-0.43324038 -0.0459173  -0.22230652]
 [-0.43324038 -0.04256963 -0.22186802]
 [-0.43324038 -0.04256963 -0.22186802]
 [-0.43324038 -0.04256963 -0.22186802]
 [-0.43324038 -0.039453   -0.2205761 ]
 [-0.43324038 -0.039453   -0.2205761 ]
 [-0.43324038 -0.039453   -0.2205761 ]
 [-0.43324038 -0.03677486 -0.21852035]
 [-0.43324038 -0.03677486 -0.21852035]
 [-0.43324038 -0.03677486 -0.21852035]
 [-0.43324038 -0.03471911 -0.21584221]
 [-0.43324038 -0.03471911 -0.21584221]
 [-0.43324038 -0.03471911 -0.21584221]
 [-0.43324038 -0.03342719

In [5]:
from torch.nn.parallel import DataParallel
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [6]:
json_dir = "/kaggle/input/dataset/pix3d.json"
with open(json_dir, 'r') as f:
    data = json.load(f)
df = pd.DataFrame(data)

In [9]:
df

img  category     img_size  \
0           img/bed/0001.png       bed   [395, 244]   
1           img/bed/0002.png       bed  [1007, 599]   
2           img/bed/0003.png       bed   [372, 292]   
3           img/bed/0004.png       bed  [1063, 755]   
4           img/bed/0005.png       bed   [414, 449]   
...                      ...       ...          ...   
10064  img/wardrobe/0239.jpg  wardrobe   [500, 500]   
10065  img/wardrobe/0240.jpg  wardrobe   [500, 500]   
10066  img/wardrobe/0241.jpg  wardrobe   [720, 960]   
10067  img/wardrobe/0242.jpg  wardrobe   [500, 500]   
10068  img/wardrobe/0243.jpg  wardrobe   [200, 200]   

                                            2d_keypoints  \
0      [[[182.5, 147.09375], [174.5, 225.09375], [16....   
1      [[[309.29285714285714, 543.9148660714286], [-1...   
2      [[[308.0, 202.09375], [-1.0, -1.0], [-1.0, -1....   
3      [[[230.06357142857144, 399.5266517857143], [93...   
4      [[[-1.0, -1.0], [-1.0, -1.0], [-1.0, -1.0], [4...   
...                                                  ...   
10064  [[[196.0, 37.09375], [268.0, 29.09375], [312.0...   
10065  [[[78.72729492, 56.09660339], [108.7272949, 54...   
10066  [[[235.2, 651.5571428571429], [491.65714285714...   
10067  [[[152.53125, 46.7265625], [311.53125, 33.7265...   
10068  [[[54.72729492, 19.09661865], [54.72729492, 19...   

                         mask img_source  \
0           mask/bed/0001.png       ikea   
1           mask/bed/0002.png       ikea   
2           mask/bed/0003.png       ikea   
3           mask/bed/0004.png       ikea   
4           mask/bed/0005.png       ikea   
...                       ...        ...   
10064  mask/wardrobe/0239.png   internet   
10065  mask/wardrobe/0240.png   internet   
10066  mask/wardrobe/0241.png       ikea   
10067  mask/wardrobe/0242.png       ikea   
10068  mask/wardrobe/0243.png       ikea   

                                         model model_raw model_source  \
0              model/bed/IKEA_MALM_2/model.obj      None         ikea   
1              model/bed/IKEA_MALM_2/model.obj      None         ikea   
2            model/bed/IKEA_HEMNES_1/model.obj      None         ikea   
3            model/bed/IKEA_HEMNES_1/model.obj      None         ikea   
4              model/bed/IKEA_MALM_2/model.obj      None         ikea   
...                                        ...       ...          ...   
10064      model/wardrobe/IKEA_PAX_3/model.obj      None         ikea   
10065      model/wardrobe/IKEA_PAX_4/model.obj      None         ikea   
10066  model/wardrobe/IKEA_ANEBODA_1/model.obj      None         ikea   
10067  model/wardrobe/IKEA_ANEBODA_1/model.obj      None         ikea   
10068  model/wardrobe/IKEA_ANEBODA_1/model.obj      None         ikea   

                                         3d_keypoints  \
0              model/bed/IKEA_MALM_2/3d_keypoints.txt   
1              model/bed/IKEA_MALM_2/3d_keypoints.txt   
2            model/bed/IKEA_HEMNES_1/3d_keypoints.txt   
3            model/bed/IKEA_HEMNES_1/3d_keypoints.txt   
4              model/bed/IKEA_MALM_2/3d_keypoints.txt   
...                                               ...   
10064      model/wardrobe/IKEA_PAX_3/3d_keypoints.txt   
10065      model/wardrobe/IKEA_PAX_4/3d_keypoints.txt   
10066  model/wardrobe/IKEA_ANEBODA_1/3d_keypoints.txt   
10067  model/wardrobe/IKEA_ANEBODA_1/3d_keypoints.txt   
10068  model/wardrobe/IKEA_ANEBODA_1/3d_keypoints.txt   

                                         voxel  \
0              model/bed/IKEA_MALM_2/voxel.mat   
1              model/bed/IKEA_MALM_2/voxel.mat   
2            model/bed/IKEA_HEMNES_1/voxel.mat   
3            model/bed/IKEA_HEMNES_1/voxel.mat   
4              model/bed/IKEA_MALM_2/voxel.mat   
...                                        ...   
10064      model/wardrobe/IKEA_PAX_3/voxel.mat   
10065      model/wardrobe/IKEA_PAX_4/voxel.mat   
10066  model/wardrobe/IKEA_ANEBODA_1/voxel.mat   
10067  model/wardrobe/IKEA_ANEBODA_1/voxel.mat   
10

In [7]:
class pix3d_dataset(Dataset):
    def __init__(self, dataframe, transform=None, data_dir='/kaggle/input/dataset/'):
        self.transform = transform
        self.dataframe = dataframe
        self.data_dir = data_dir

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        img_path = self.data_dir + self.dataframe.iloc[idx]['img']
        mask_path = self.data_dir + self.dataframe.iloc[idx]['mask']
        voxel_path = self.data_dir + self.dataframe.iloc[idx]['voxel']

        image = Image.open(img_path).convert('RGB')
        mask = Image.open(mask_path).convert('L')
        voxel = scipy.io.loadmat(voxel_path)['voxel']

        if self.transform:
            image = self.transform(image)
            mask = self.transform(mask)

        voxel = torch.tensor(voxel, dtype=torch.float32).unsqueeze(0)
        sample = {
            'image': image,
            'mask': mask,
            'voxel': voxel
        }
        return sample


In [8]:
latent_dim = 100
hidden_dim = 64
lr = 0.0002
batch_size = 1
num_epochs = 2

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
])
dataset = pix3d_dataset(df, transform = transform)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=0)

generator = Generator(img_dim=3, hidden_dim=hidden_dim, latent_dim=latent_dim, output_dim=128).to(device)
# if torch.cuda.device_count() > 1:
#     generator = torch.nn.DataParallel(generator)
generator = generator.to('cuda:0')
discriminator = Discriminator(voxel_dim=1, img_dim=3, hidden_dim=hidden_dim).to(device)
# if torch.cuda.device_count() > 1:
#     discriminator = torch.nn.DataParallel(discriminator)
discriminator = discriminator.to("cuda:1")
optimizer_g = optim.SGD(generator.parameters(), lr=lr)
optimizer_d = optim.SGD(generator.parameters(), lr=lr)
criterion = nn.BCELoss()

In [9]:
for i, data in enumerate(dataloader):
    real_images = data['image'].to(device)
    real_voxels = data['voxel'].to(device)
    print("Image shape:", real_images.shape)
    print("Voxel shape:", real_voxels.shape)
    break

Image shape: torch.Size([1, 3, 128, 128])
Voxel shape: torch.Size([1, 1, 128, 128, 128])


In [10]:
import tqdm as tqdm

In [11]:
for epoch in tqdm.tqdm(range(num_epochs)):
    for i, data in enumerate(dataloader):
        real_images = data['image'].to(device)
        real_voxels = data['voxel'].to(device)

        print(f"Real images shape: {real_images.shape}")
        print(f"Real voxels shape: {real_voxels.shape}")

        batch_size = real_images.size(0)
        real_labels = torch.ones(batch_size, 1).to(device)
        fake_labels = torch.zeros(batch_size, 1).to(device)

        #trainign Discriminator
        optimizer_d.zero_grad()

        #real data
        outputs = discriminator(real_voxels, real_images)
        d_loss_real = criterion(outputs, real_labels)

        #fake data
        z = torch.randn(batch_size, latent_dim).to(device)
        fake_voxels = generator(real_images, z)

        print(f"Fake voxels shape: {fake_voxels.shape}")

        outputs = discriminator(fake_voxels.detach(), real_images)
        d_loss_fake = criterion(outputs, fake_labels)

        d_loss = d_loss_real + d_loss_fake
        d_loss.backward()
        optimizer_d.step()

        optimizer_g.zero_grad()

        fake_voxels = generator(real_images, z)
        outputs = discriminator(fake_voxels, real_images)
        g_loss = criterion(outputs, real_labels)

        g_loss.backward()
        optimizer_g.step()

        if (i + 1) % 100 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(dataloader)}], D Loss: {d_loss.item()}, G Loss: {g_loss.item()}")

    torch.save(generator.state_dict(), f'generator_epoch_{epoch+1}.pth')
    torch.save(discriminator.state_dict(), f'discriminator_epoch_{epoch+1}.pth')

  0%|          | 0/2 [00:00<?, ?it/s]


Real images shape: torch.Size([1, 3, 128, 128])
Real voxels shape: torch.Size([1, 1, 128, 128, 128])


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)